//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class nrc_interface {
  public static int robotNum {
    get {
      int ret = nrc_interfacePINVOKE.robotNum_get();
      return ret;
    } 
  }

  public static int connect_robot(string ip, string port) {
    int ret = nrc_interfacePINVOKE.connect_robot(ip, port);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int disconnect_robot(int socketFd) {
    int ret = nrc_interfacePINVOKE.disconnect_robot(socketFd);
    return ret;
  }

  public static int get_connection_status(int socketFd) {
    int ret = nrc_interfacePINVOKE.get_connection_status(socketFd);
    return ret;
  }

  public static int send_message(int socketFd, int messageID, string message) {
    int ret = nrc_interfacePINVOKE.send_message(socketFd, messageID, message);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int recv_message(int socketFd, SWIGTYPE_p_f_int_r_std__string__void callback) {
    int ret = nrc_interfacePINVOKE.recv_message(socketFd, SWIGTYPE_p_f_int_r_std__string__void.getCPtr(callback));
    return ret;
  }

  public static int clear_error(int socketFd) {
    int ret = nrc_interfacePINVOKE.clear_error(socketFd);
    return ret;
  }

  public static int set_servo_state(int socketFd, int state) {
    int ret = nrc_interfacePINVOKE.set_servo_state(socketFd, state);
    return ret;
  }

  public static int get_servo_state(int socketFd) {
    int ret = nrc_interfacePINVOKE.get_servo_state(socketFd);
    return ret;
  }

  public static int set_servo_poweron(int socketFd) {
    int ret = nrc_interfacePINVOKE.set_servo_poweron(socketFd);
    return ret;
  }

  public static int set_servo_poweroff(int socketFd) {
    int ret = nrc_interfacePINVOKE.set_servo_poweroff(socketFd);
    return ret;
  }

  public static int get_current_position(int socketFd, int coord, DoubleVector pos) {
    int ret = nrc_interfacePINVOKE.get_current_position(socketFd, coord, DoubleVector.getCPtr(pos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_current_extra_position(int socketFd, DoubleVector pos) {
    int ret = nrc_interfacePINVOKE.get_current_extra_position(socketFd, DoubleVector.getCPtr(pos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_robot_running_state(int socketFd) {
    int ret = nrc_interfacePINVOKE.get_robot_running_state(socketFd);
    return ret;
  }

  public static int set_speed(int socketFd, int speed) {
    int ret = nrc_interfacePINVOKE.set_speed(socketFd, speed);
    return ret;
  }

  public static int get_speed(int socketFd) {
    int ret = nrc_interfacePINVOKE.get_speed(socketFd);
    return ret;
  }

  public static int set_current_coord(int socketFd, int coord) {
    int ret = nrc_interfacePINVOKE.set_current_coord(socketFd, coord);
    return ret;
  }

  public static int get_current_coord(int socketFd) {
    int ret = nrc_interfacePINVOKE.get_current_coord(socketFd);
    return ret;
  }

  public static int set_current_mode(int socketFd, int mode) {
    int ret = nrc_interfacePINVOKE.set_current_mode(socketFd, mode);
    return ret;
  }

  public static int get_current_mode(int socketFd) {
    int ret = nrc_interfacePINVOKE.get_current_mode(socketFd);
    return ret;
  }

  public static int set_digital_output(int socketFd, int port, int value) {
    int ret = nrc_interfacePINVOKE.set_digital_output(socketFd, port, value);
    return ret;
  }

  public static int get_digital_output(int socketFd, IntVector out_) {
    int ret = nrc_interfacePINVOKE.get_digital_output(socketFd, IntVector.getCPtr(out_));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_digital_input(int socketFd, IntVector in_) {
    int ret = nrc_interfacePINVOKE.get_digital_input(socketFd, IntVector.getCPtr(in_));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_analog_output(int socketFd, int port, double value) {
    int ret = nrc_interfacePINVOKE.set_analog_output(socketFd, port, value);
    return ret;
  }

  public static int get_analog_output(int socketFd, DoubleVector aout) {
    int ret = nrc_interfacePINVOKE.get_analog_output(socketFd, DoubleVector.getCPtr(aout));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_analog_input(int socketFd, DoubleVector ain) {
    int ret = nrc_interfacePINVOKE.get_analog_input(socketFd, DoubleVector.getCPtr(ain));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_force_digital_input(int socketFd, int port, int force, int value) {
    int ret = nrc_interfacePINVOKE.set_force_digital_input(socketFd, port, force, value);
    return ret;
  }

  public static int get_force_digital_input(int socketFd, IntVector port, DoubleVector status) {
    int ret = nrc_interfacePINVOKE.get_force_digital_input(socketFd, IntVector.getCPtr(port), DoubleVector.getCPtr(status));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_tool_hand_number(int socketFd, int toolNum) {
    int ret = nrc_interfacePINVOKE.set_tool_hand_number(socketFd, toolNum);
    return ret;
  }

  public static int get_tool_hand_number(int socketFd, ref int toolNum) {
    int ret = nrc_interfacePINVOKE.get_tool_hand_number(socketFd, ref toolNum);
    return ret;
  }

  public static int set_tool_hand_param(int socketFd, int toolNum, ToolParam param) {
    int ret = nrc_interfacePINVOKE.set_tool_hand_param(socketFd, toolNum, ToolParam.getCPtr(param));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_tool_hand_param(int socketFd, int toolNum, ToolParam param) {
    int ret = nrc_interfacePINVOKE.get_tool_hand_param(socketFd, toolNum, ToolParam.getCPtr(param));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_user_coord_number(int socketFd, int userNum) {
    int ret = nrc_interfacePINVOKE.set_user_coord_number(socketFd, userNum);
    return ret;
  }

  public static int get_user_coord_number(int socketFd, ref int userNum) {
    int ret = nrc_interfacePINVOKE.get_user_coord_number(socketFd, ref userNum);
    return ret;
  }

  public static int get_user_coord_para(int socketFd, int userNum, DoubleVector pos) {
    int ret = nrc_interfacePINVOKE.get_user_coord_para(socketFd, userNum, DoubleVector.getCPtr(pos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_global_position(int socketFd, string posName, DoubleVector posInfo) {
    int ret = nrc_interfacePINVOKE.set_global_position(socketFd, posName, DoubleVector.getCPtr(posInfo));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_global_position(int socketFd, string posName, DoubleVector pos) {
    int ret = nrc_interfacePINVOKE.get_global_position(socketFd, posName, DoubleVector.getCPtr(pos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_global_sync_position(int socketFd, string posName, DoubleVector posInfo) {
    int ret = nrc_interfacePINVOKE.set_global_sync_position(socketFd, posName, DoubleVector.getCPtr(posInfo));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_global_sync_position(int socketFd, string posName, DoubleVector pos) {
    int ret = nrc_interfacePINVOKE.get_global_sync_position(socketFd, posName, DoubleVector.getCPtr(pos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_global_variant(int socketFd, string varName, double varValue) {
    int ret = nrc_interfacePINVOKE.set_global_variant(socketFd, varName, varValue);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_global_variant(int socketFd, string varName, ref double vaule) {
    int ret = nrc_interfacePINVOKE.get_global_variant(socketFd, varName, ref vaule);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_local_position(int socketFd, string posName, DoubleVector posInfo) {
    int ret = nrc_interfacePINVOKE.set_local_position(socketFd, posName, DoubleVector.getCPtr(posInfo));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_axis_zero_position(int socketFd, int axis) {
    int ret = nrc_interfacePINVOKE.set_axis_zero_position(socketFd, axis);
    return ret;
  }

  public static int set_zero_pos_deviation(int socketFd, int axis, double shift) {
    int ret = nrc_interfacePINVOKE.set_zero_pos_deviation(socketFd, axis, shift);
    return ret;
  }

  public static int get_single_cycle(int socketFd, DoubleVector single_cycle) {
    int ret = nrc_interfacePINVOKE.get_single_cycle(socketFd, DoubleVector.getCPtr(single_cycle));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_four_point(int socketFd, DoubleVector result) {
    int ret = nrc_interfacePINVOKE.get_four_point(socketFd, DoubleVector.getCPtr(result));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_four_point_mark(int socketFd, int point, int status) {
    int ret = nrc_interfacePINVOKE.set_four_point_mark(socketFd, point, status);
    return ret;
  }

  public static int four_point_calculation(int socketFd, double L1, double L2, DoubleVector result) {
    int ret = nrc_interfacePINVOKE.four_point_calculation(socketFd, L1, L2, DoubleVector.getCPtr(result));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_result_for_DH(int socketFd, ref int apply) {
    int ret = nrc_interfacePINVOKE.set_result_for_DH(socketFd, ref apply);
    return ret;
  }

  public static int set_receive_error_or_warnning_message_callback(int socketFd, SWIGTYPE_p_f_int_r_q_const__std__string_int__void function) {
    int ret = nrc_interfacePINVOKE.set_receive_error_or_warnning_message_callback(socketFd, SWIGTYPE_p_f_int_r_q_const__std__string_int__void.getCPtr(function));
    return ret;
  }

  public static int get_origin_coord_to_target_coord(int socketFd, int originCoord, DoubleVector originPos, int targetCoord, DoubleVector targetPos) {
    int ret = nrc_interfacePINVOKE.get_origin_coord_to_target_coord(socketFd, originCoord, DoubleVector.getCPtr(originPos), targetCoord, DoubleVector.getCPtr(targetPos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_robot_dh_param(int socketFd, RobotDHParam param) {
    int ret = nrc_interfacePINVOKE.get_robot_dh_param(socketFd, RobotDHParam.getCPtr(param));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_robot_joint_param(int socketFd, int id, RobotJointParam param) {
    int ret = nrc_interfacePINVOKE.get_robot_joint_param(socketFd, id, RobotJointParam.getCPtr(param));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int set_user_coordinate_data(int socketFd, int userNumber, DoubleVector pos) {
    int ret = nrc_interfacePINVOKE.set_user_coordinate_data(socketFd, userNumber, DoubleVector.getCPtr(pos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int calibration_oxy(int socketFd, int userNumber, string xyo) {
    int ret = nrc_interfacePINVOKE.calibration_oxy(socketFd, userNumber, xyo);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int calculate_user_coordinate(int socketFd, int userNumber) {
    int ret = nrc_interfacePINVOKE.calculate_user_coordinate(socketFd, userNumber);
    return ret;
  }

  public static int get_teachbox_connection_status(int socketFd) {
    int ret = nrc_interfacePINVOKE.get_teachbox_connection_status(socketFd);
    return ret;
  }

  public static int set_teach_box_disconnected(int socketFd) {
    int ret = nrc_interfacePINVOKE.set_teach_box_disconnected(socketFd);
    return ret;
  }

  public static int set_hard_enable_port(int socketFd, int enable, int port1, int port2) {
    int ret = nrc_interfacePINVOKE.set_hard_enable_port(socketFd, enable, port1, port2);
    return ret;
  }

  public static int get_hard_enable_port(int socketFd, ref int enable, ref int port1, ref int port2) {
    int ret = nrc_interfacePINVOKE.get_hard_enable_port(socketFd, ref enable, ref port1, ref port2);
    return ret;
  }

  public static int get_controller_id(int socketFd, SWIGTYPE_p_std__string id) {
    int ret = nrc_interfacePINVOKE.get_controller_id(socketFd, SWIGTYPE_p_std__string.getCPtr(id));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int robot_start_jogging(int socketFd, int axis, bool dir) {
    int ret = nrc_interfacePINVOKE.robot_start_jogging(socketFd, axis, dir);
    return ret;
  }

  public static int robot_stop_jogging(int socketFd, int axis) {
    int ret = nrc_interfacePINVOKE.robot_stop_jogging(socketFd, axis);
    return ret;
  }

  public static int robot_go_to_reset_position(int socketFd) {
    int ret = nrc_interfacePINVOKE.robot_go_to_reset_position(socketFd);
    return ret;
  }

  public static int robot_go_home(int socketFd) {
    int ret = nrc_interfacePINVOKE.robot_go_home(socketFd);
    return ret;
  }

  public static int robot_movej(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.robot_movej(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int robot_movel(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.robot_movel(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int robot_movec(int socketFd, DoubleVector pos1, DoubleVector pos2, DoubleVector pos3, int vel, int coord, int acc, int dec) {
    int ret = nrc_interfacePINVOKE.robot_movec(socketFd, DoubleVector.getCPtr(pos1), DoubleVector.getCPtr(pos2), DoubleVector.getCPtr(pos3), vel, coord, acc, dec);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int robot_moves(int socketFd, VectorVectorDouble pos, int vel, int coord, int acc, int dec) {
    int ret = nrc_interfacePINVOKE.robot_moves(socketFd, VectorVectorDouble.getCPtr(pos), vel, coord, acc, dec);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int robot_extra_movej(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.robot_extra_movej(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int robot_extra_movel(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.robot_extra_movel(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int robot_extra_movec(int socketFd, DoubleVector pos1, DoubleVector pos2, DoubleVector pos3, int vel, int coord, int acc, int dec) {
    int ret = nrc_interfacePINVOKE.robot_extra_movec(socketFd, DoubleVector.getCPtr(pos1), DoubleVector.getCPtr(pos2), DoubleVector.getCPtr(pos3), vel, coord, acc, dec);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_current_position_hydraulic(int socketFd, DoubleVector currentLength, int coord, DoubleVector pos, int mode) {
    int ret = nrc_interfacePINVOKE.get_current_position_hydraulic(socketFd, DoubleVector.getCPtr(currentLength), coord, DoubleVector.getCPtr(pos), mode);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int robot_move_hydraulic(int socketFd, int moveType, DoubleVector currentLength, DoubleVector pos, int vel, int coord, int acc, int dec) {
    int ret = nrc_interfacePINVOKE.robot_move_hydraulic(socketFd, moveType, DoubleVector.getCPtr(currentLength), DoubleVector.getCPtr(pos), vel, coord, acc, dec);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int get_planning_position_hydraulic(int socketFd, VectorVectorDouble pos) {
    int ret = nrc_interfacePINVOKE.get_planning_position_hydraulic(socketFd, VectorVectorDouble.getCPtr(pos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_upload_by_directory(int socketFd, string directoryPath) {
    int ret = nrc_interfacePINVOKE.job_upload_by_directory(socketFd, directoryPath);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_upload_by_file(int socketFd, string filePath) {
    int ret = nrc_interfacePINVOKE.job_upload_by_file(socketFd, filePath);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_download_by_directory(int socketFd, string directoryPath, bool isCover) {
    int ret = nrc_interfacePINVOKE.job_download_by_directory(socketFd, directoryPath, isCover);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int log_download_by_quantity(int socketFd, int counts, string directoryPath) {
    int ret = nrc_interfacePINVOKE.log_download_by_quantity(socketFd, counts, directoryPath);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int backup_system(int socketFd) {
    int ret = nrc_interfacePINVOKE.backup_system(socketFd);
    return ret;
  }

  public static int job_delete(int socketFd, string jobName) {
    int ret = nrc_interfacePINVOKE.job_delete(socketFd, jobName);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_open(int socketFd, string jobName) {
    int ret = nrc_interfacePINVOKE.job_open(socketFd, jobName);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_run(int socketFd, string jobName) {
    int ret = nrc_interfacePINVOKE.job_run(socketFd, jobName);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_step(int socketFd, string jobName, int line) {
    int ret = nrc_interfacePINVOKE.job_step(socketFd, jobName, line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_pause(int socketFd) {
    int ret = nrc_interfacePINVOKE.job_pause(socketFd);
    return ret;
  }

  public static int job_continue(int socketFd) {
    int ret = nrc_interfacePINVOKE.job_continue(socketFd);
    return ret;
  }

  public static int job_stop(int socketFd) {
    int ret = nrc_interfacePINVOKE.job_stop(socketFd);
    return ret;
  }

  public static int job_run_times(int socketFd, int index) {
    int ret = nrc_interfacePINVOKE.job_run_times(socketFd, index);
    return ret;
  }

  public static int job_break_point_run(int socketFd, string jobName) {
    int ret = nrc_interfacePINVOKE.job_break_point_run(socketFd, jobName);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_get_current_file(int socketFd, SWIGTYPE_p_std__string jobname) {
    int ret = nrc_interfacePINVOKE.job_get_current_file(socketFd, SWIGTYPE_p_std__string.getCPtr(jobname));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_get_current_line(int socketFd) {
    int ret = nrc_interfacePINVOKE.job_get_current_line(socketFd);
    return ret;
  }

  public static int job_sync_job_file(int socketFd) {
    int ret = nrc_interfacePINVOKE.job_sync_job_file(socketFd);
    return ret;
  }

  public static int job_insert_timer_command(int socketFd, int pos, double tm) {
    int ret = nrc_interfacePINVOKE.job_insert_timer_command(socketFd, pos, tm);
    return ret;
  }

  public static int job_insert_vision_craft_start(int socketFd, int id, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_vision_craft_start(socketFd, id, line);
    return ret;
  }

  public static int job_insert_vision_craft_get_pos(int socketFd, int id, string posName, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_vision_craft_get_pos(socketFd, id, posName, line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_vision_craft_visual_trigger(int socketFd, int id, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_vision_craft_visual_trigger(socketFd, id, line);
    return ret;
  }

  public static int job_insert_vision_craft_visual_end(int socketFd, int id, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_vision_craft_visual_end(socketFd, id, line);
    return ret;
  }

  public static int job_insert_conveyor_check_pos(int socketFd, int id, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_conveyor_check_pos(socketFd, id, line);
    return ret;
  }

  public static int job_insert_conveyor_check_end(int socketFd, int id, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_conveyor_check_end(socketFd, id, line);
    return ret;
  }

  public static int job_insert_conveyor_on(int socketFd, int id, int postype, DoubleVector pos, int vel, int acc, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_conveyor_on(socketFd, id, postype, DoubleVector.getCPtr(pos), vel, acc, line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_conveyor_off(int socketFd, int id, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_conveyor_off(socketFd, id, line);
    return ret;
  }

  public static int job_insert_conveyor_pos(int socketFd, int id, string posName, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_conveyor_pos(socketFd, id, posName, line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_conveyor_clear(int socketFd, int id, int removeType, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_conveyor_clear(socketFd, id, removeType, line);
    return ret;
  }

  public static int job_insert_moveJ(int socketFd, MoveCmd moveCmd, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_moveJ(socketFd, MoveCmd.getCPtr(moveCmd), line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_moveL(int socketFd, MoveCmd moveCmd, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_moveL(socketFd, MoveCmd.getCPtr(moveCmd), line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_moveC(int socketFd, MoveCmd moveCmd, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_moveC(socketFd, MoveCmd.getCPtr(moveCmd), line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_until(int socketFd, VectorVectorCondition conditionGroups, IntVector logic, VectorVectorInt logicGroup, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_until(socketFd, VectorVectorCondition.getCPtr(conditionGroups), IntVector.getCPtr(logic), VectorVectorInt.getCPtr(logicGroup), line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_end_until(int socketFd, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_end_until(socketFd, line);
    return ret;
  }

  public static int job_insert_while(int socketFd, VectorVectorCondition conditionGroups, IntVector logic, VectorVectorInt logicGroup, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_while(socketFd, VectorVectorCondition.getCPtr(conditionGroups), IntVector.getCPtr(logic), VectorVectorInt.getCPtr(logicGroup), line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_end_while(int socketFd, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_end_while(socketFd, line);
    return ret;
  }

  public static int job_insert_if(int socketFd, VectorVectorCondition conditionGroups, IntVector logic, VectorVectorInt logicGroup, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_if(socketFd, VectorVectorCondition.getCPtr(conditionGroups), IntVector.getCPtr(logic), VectorVectorInt.getCPtr(logicGroup), line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_end_if(int socketFd, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_end_if(socketFd, line);
    return ret;
  }

  public static int job_insert_label(int socketFd, string label, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_label(socketFd, label, line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_jump(int socketFd, VectorVectorCondition conditionGroups, IntVector logic, VectorVectorInt logicGroup, bool jumpConditionFlag, string label, int line) {
    int ret = nrc_interfacePINVOKE.job_insert_jump(socketFd, VectorVectorCondition.getCPtr(conditionGroups), IntVector.getCPtr(logic), VectorVectorInt.getCPtr(logicGroup), jumpConditionFlag, label, line);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int job_insert_io_out_command(int socketFd, int pos, IOCommandParams params_) {
    int ret = nrc_interfacePINVOKE.job_insert_io_out_command(socketFd, pos, IOCommandParams.getCPtr(params_));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_set_status(int socketFd, bool status) {
    int ret = nrc_interfacePINVOKE.queue_motion_set_status(socketFd, status);
    return ret;
  }

  public static int queue_motion_get_status(int socketFd, SWIGTYPE_p_bool status) {
    int ret = nrc_interfacePINVOKE.queue_motion_get_status(socketFd, SWIGTYPE_p_bool.getCPtr(status));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_send_to_controller(int socketFd, int size) {
    int ret = nrc_interfacePINVOKE.queue_motion_send_to_controller(socketFd, size);
    return ret;
  }

  public static int queue_motion_suspend(int socketFd) {
    int ret = nrc_interfacePINVOKE.queue_motion_suspend(socketFd);
    return ret;
  }

  public static int queue_motion_restart(int socketFd) {
    int ret = nrc_interfacePINVOKE.queue_motion_restart(socketFd);
    return ret;
  }

  public static int queue_motion_stop(int socketFd) {
    int ret = nrc_interfacePINVOKE.queue_motion_stop(socketFd);
    return ret;
  }

  public static int queue_motion_push_back_moveJ(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_moveJ(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_moveL(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_moveL(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_moveC(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_moveC(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_moveCA(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_moveCA(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_moveJ_extra(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_moveJ_extra(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_moveL_extra(int socketFd, MoveCmd moveCmd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_moveL_extra(socketFd, MoveCmd.getCPtr(moveCmd));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_timer(int socketFd, double time) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_timer(socketFd, time);
    return ret;
  }

  public static int queue_motion_push_back_dout(int socketFd, int port, bool value) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_dout(socketFd, port, value);
    return ret;
  }

  public static int queue_motion_push_back_conveyor_check_pos(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_conveyor_check_pos(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_conveyor_check_end(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_conveyor_check_end(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_conveyor_on(int socketFd, int id, int postype, DoubleVector pos, int vel, int acc) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_conveyor_on(socketFd, id, postype, DoubleVector.getCPtr(pos), vel, acc);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_conveyor_off(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_conveyor_off(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_conveyor_pos(int socketFd, int id, string posName) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_conveyor_pos(socketFd, id, posName);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_conveyor_clear(int socketFd, int id, int removeType) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_conveyor_clear(socketFd, id, removeType);
    return ret;
  }

  public static int queue_motion_push_back_arc_on(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_arc_on(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_arc_off(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_arc_off(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_wave_on(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_wave_on(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_wave_off(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_wave_off(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_tigweld_on(int socketFd, int type, double l1, double l2) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_tigweld_on(socketFd, type, l1, l2);
    return ret;
  }

  public static int queue_motion_push_back_tigweld_off(int socketFd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_tigweld_off(socketFd);
    return ret;
  }

  public static int queue_motion_push_back_spot_weld(int socketFd, int id, double time) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_spot_weld(socketFd, id, time);
    return ret;
  }

  public static int queue_motion_push_back_vision_craft_start(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_vision_craft_start(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_vision_craft_get_pos(int socketFd, int id, string posName) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_vision_craft_get_pos(socketFd, id, posName);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_vision_craft_visual_trigger(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_vision_craft_visual_trigger(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_vision_craft_visual_end(int socketFd, int id) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_vision_craft_visual_end(socketFd, id);
    return ret;
  }

  public static int queue_motion_push_back_until(int socketFd, VectorVectorCondition conditionGroups, IntVector logic, VectorVectorInt logicGroup) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_until(socketFd, VectorVectorCondition.getCPtr(conditionGroups), IntVector.getCPtr(logic), VectorVectorInt.getCPtr(logicGroup));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_end_until(int socketFd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_end_until(socketFd);
    return ret;
  }

  public static int queue_motion_push_back_while(int socketFd, VectorVectorCondition conditionGroups, IntVector logic, VectorVectorInt logicGroup) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_while(socketFd, VectorVectorCondition.getCPtr(conditionGroups), IntVector.getCPtr(logic), VectorVectorInt.getCPtr(logicGroup));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_end_while(int socketFd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_end_while(socketFd);
    return ret;
  }

  public static int queue_motion_push_back_if(int socketFd, VectorVectorCondition conditionGroups, IntVector logic, VectorVectorInt logicGroup) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_if(socketFd, VectorVectorCondition.getCPtr(conditionGroups), IntVector.getCPtr(logic), VectorVectorInt.getCPtr(logicGroup));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_end_if(int socketFd) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_end_if(socketFd);
    return ret;
  }

  public static int queue_motion_push_back_label(int socketFd, string label) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_label(socketFd, label);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int queue_motion_push_back_jump(int socketFd, VectorVectorCondition conditionGroups, IntVector logic, VectorVectorInt logicGroup, bool jumpConditionFlag, string label) {
    int ret = nrc_interfacePINVOKE.queue_motion_push_back_jump(socketFd, VectorVectorCondition.getCPtr(conditionGroups), IntVector.getCPtr(logic), VectorVectorInt.getCPtr(logicGroup), jumpConditionFlag, label);
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int conveyor_belt_tracking_set_basic_parameter(int socketFd, int encoderVal, int time, int encoderDirection, double encoderResolution, double maxEncoderVal, double minEncoderVal, int posRecordMode, double speed, int userCoord, int conveyorID, int height, int trackOnRunModeWithTargetOverrun, int compensationEncoderVal) {
    int ret = nrc_interfacePINVOKE.conveyor_belt_tracking_set_basic_parameter(socketFd, encoderVal, time, encoderDirection, encoderResolution, maxEncoderVal, minEncoderVal, posRecordMode, speed, userCoord, conveyorID, height, trackOnRunModeWithTargetOverrun, compensationEncoderVal);
    return ret;
  }

  public static int conveyor_belt_tracking_set_identification_parameter(int socketFd, int conveyorID, int detectSrcType, int capturePos, int visionID, int visionIoFilterType, int visionLatchEncoderValueType, int communication, int sensorTrg, int type) {
    int ret = nrc_interfacePINVOKE.conveyor_belt_tracking_set_identification_parameter(socketFd, conveyorID, detectSrcType, capturePos, visionID, visionIoFilterType, visionLatchEncoderValueType, communication, sensorTrg, type);
    return ret;
  }

  public static int conveyor_belt_tracking_set_sensor_calibration(int socketFd, int conveyorID, DoubleVector sensorPos) {
    int ret = nrc_interfacePINVOKE.conveyor_belt_tracking_set_sensor_calibration(socketFd, conveyorID, DoubleVector.getCPtr(sensorPos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int conveyor_belt_tracking_set_tracking_range(int socketFd, int conveyorID, double receLatestPos, double trackRangeXMax, double trackRangeYMax, double trackRangeYMin, double trackRangeZMax, double trackRangeZMin, double trackStartXPoint) {
    int ret = nrc_interfacePINVOKE.conveyor_belt_tracking_set_tracking_range(socketFd, conveyorID, receLatestPos, trackRangeXMax, trackRangeYMax, trackRangeYMin, trackRangeZMax, trackRangeZMin, trackStartXPoint);
    return ret;
  }

  public static int conveyor_belt_tracking_set_tracking_wait_point(int socketFd, int conveyorID, bool isWait, double delayDetectTime, DoubleVector pos) {
    int ret = nrc_interfacePINVOKE.conveyor_belt_tracking_set_tracking_wait_point(socketFd, conveyorID, isWait, delayDetectTime, DoubleVector.getCPtr(pos));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int conveyor_belt_set_sensor_calibration(int socketFd, int conveyorID) {
    int ret = nrc_interfacePINVOKE.conveyor_belt_set_sensor_calibration(socketFd, conveyorID);
    return ret;
  }

  public static int conveyor_belt_calibrate_for_sensor_point(int socketFd, int conveyorID) {
    int ret = nrc_interfacePINVOKE.conveyor_belt_calibrate_for_sensor_point(socketFd, conveyorID);
    return ret;
  }

  public static int conveyor_belt_calculate_for_sensor_point(int socketFd, int conveyorID) {
    int ret = nrc_interfacePINVOKE.conveyor_belt_calculate_for_sensor_point(socketFd, conveyorID);
    return ret;
  }

  public static int weld_get_config(int socketFd, int index, ArcParam param) {
    int ret = nrc_interfacePINVOKE.weld_get_config(socketFd, index, ArcParam.getCPtr(param));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int weld_set_config(int socketFd, int index, ArcParam param) {
    int ret = nrc_interfacePINVOKE.weld_set_config(socketFd, index, ArcParam.getCPtr(param));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int weld_set_feed_wire(int socketFd, int state) {
    int ret = nrc_interfacePINVOKE.weld_set_feed_wire(socketFd, state);
    return ret;
  }

  public static int weld_set_rewind_wire(int socketFd, int state) {
    int ret = nrc_interfacePINVOKE.weld_set_rewind_wire(socketFd, state);
    return ret;
  }

  public static int weld_set_supply_gas(int socketFd, int state) {
    int ret = nrc_interfacePINVOKE.weld_set_supply_gas(socketFd, state);
    return ret;
  }

  public static int weld_set_enable(int socketFd, int state) {
    int ret = nrc_interfacePINVOKE.weld_set_enable(socketFd, state);
    return ret;
  }

  public static int weld_set_hand_spot(int socketFd, int state) {
    int ret = nrc_interfacePINVOKE.weld_set_hand_spot(socketFd, state);
    return ret;
  }

  public static int weld_get_feed_wire_status(int socketFd, IntVector status) {
    int ret = nrc_interfacePINVOKE.weld_get_feed_wire_status(socketFd, IntVector.getCPtr(status));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int weld_get_wave_weld_param(int socketFd, int num, WaveParam param) {
    int ret = nrc_interfacePINVOKE.weld_get_wave_weld_param(socketFd, num, WaveParam.getCPtr(param));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int weld_set_wave_weld_param(int socketFd, int num, WaveParam param) {
    int ret = nrc_interfacePINVOKE.weld_set_wave_weld_param(socketFd, num, WaveParam.getCPtr(param));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int weld_get_monitor_status(int socketFd, WeldState status) {
    int ret = nrc_interfacePINVOKE.weld_get_monitor_status(socketFd, WeldState.getCPtr(status));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int vision_set_basic_parameter(int socketFd, int visionNum, VisionParam vsPamrm) {
    int ret = nrc_interfacePINVOKE.vision_set_basic_parameter(socketFd, visionNum, VisionParam.getCPtr(vsPamrm));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int vision_get_basic_parameter(int socketFd, int visionNum, VisionParam vsPamrm) {
    int ret = nrc_interfacePINVOKE.vision_get_basic_parameter(socketFd, visionNum, VisionParam.getCPtr(vsPamrm));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int vision_set_range(int socketFd, int visionNum, VisionRange vsPamrm) {
    int ret = nrc_interfacePINVOKE.vision_set_range(socketFd, visionNum, VisionRange.getCPtr(vsPamrm));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int vision_get_range(int socketFd, int visionNum, VisionRange vsPamrm) {
    int ret = nrc_interfacePINVOKE.vision_get_range(socketFd, visionNum, VisionRange.getCPtr(vsPamrm));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int vision_set_position_parameter(int socketFd, int visionNum, VisionPositionParam vsPamrm) {
    int ret = nrc_interfacePINVOKE.vision_set_position_parameter(socketFd, visionNum, VisionPositionParam.getCPtr(vsPamrm));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int vision_get_position_parameter(int socketFd, int visionId, VisionPositionParam vsPamrm) {
    int ret = nrc_interfacePINVOKE.vision_get_position_parameter(socketFd, visionId, VisionPositionParam.getCPtr(vsPamrm));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int vision_calibrate(int socketFd, int visionId, VisionCalibrationData vsPamrm) {
    int ret = nrc_interfacePINVOKE.vision_calibrate(socketFd, visionId, VisionCalibrationData.getCPtr(vsPamrm));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int vision_get_calibrate_data(int socketFd, int visionId, VisionCalibrationData vsPamrm) {
    int ret = nrc_interfacePINVOKE.vision_get_calibrate_data(socketFd, visionId, VisionCalibrationData.getCPtr(vsPamrm));
    if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int vision_hand_eye_calibration_calculation(int socketFd, int visionNum) {
    int ret = nrc_interfacePINVOKE.vision_hand_eye_calibration_calculation(socketFd, visionNum);
    return ret;
  }

}
