//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RobotDHParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RobotDHParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RobotDHParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RobotDHParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RobotDHParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_RobotDHParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double L1 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L1_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L1_get(swigCPtr);
      return ret;
    } 
  }

  public double L2 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L2_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L2_get(swigCPtr);
      return ret;
    } 
  }

  public double L3 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L3_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L3_get(swigCPtr);
      return ret;
    } 
  }

  public double L4 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L4_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L4_get(swigCPtr);
      return ret;
    } 
  }

  public double L5 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L5_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L5_get(swigCPtr);
      return ret;
    } 
  }

  public double L6 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L6_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L6_get(swigCPtr);
      return ret;
    } 
  }

  public double L7 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L7_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L7_get(swigCPtr);
      return ret;
    } 
  }

  public double L8 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_L8_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_L8_get(swigCPtr);
      return ret;
    } 
  }

  public double coupleCoe_1_2 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_coupleCoe_1_2_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_coupleCoe_1_2_get(swigCPtr);
      return ret;
    } 
  }

  public double coupleCoe_2_3 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_coupleCoe_2_3_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_coupleCoe_2_3_get(swigCPtr);
      return ret;
    } 
  }

  public double coupleCoe_3_2 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_coupleCoe_3_2_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_coupleCoe_3_2_get(swigCPtr);
      return ret;
    } 
  }

  public double coupleCoe_3_4 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_coupleCoe_3_4_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_coupleCoe_3_4_get(swigCPtr);
      return ret;
    } 
  }

  public double coupleCoe_4_5 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_coupleCoe_4_5_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_coupleCoe_4_5_get(swigCPtr);
      return ret;
    } 
  }

  public double coupleCoe_4_6 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_coupleCoe_4_6_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_coupleCoe_4_6_get(swigCPtr);
      return ret;
    } 
  }

  public double coupleCoe_5_6 {
    set {
      nrc_interfacePINVOKE.RobotDHParam_coupleCoe_5_6_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_coupleCoe_5_6_get(swigCPtr);
      return ret;
    } 
  }

  public double fiveAxisDirection {
    set {
      nrc_interfacePINVOKE.RobotDHParam_fiveAxisDirection_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_fiveAxisDirection_get(swigCPtr);
      return ret;
    } 
  }

  public double threeAxisDirection {
    set {
      nrc_interfacePINVOKE.RobotDHParam_threeAxisDirection_set(swigCPtr, value);
    } 
    get {
      double ret = nrc_interfacePINVOKE.RobotDHParam_threeAxisDirection_get(swigCPtr);
      return ret;
    } 
  }

  public RobotDHParam() : this(nrc_interfacePINVOKE.new_RobotDHParam(), true) {
  }

}
