//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VisionPositionParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VisionPositionParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VisionPositionParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VisionPositionParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VisionPositionParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VisionPositionParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public class Position : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal Position(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Position obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Position obj) {
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
        global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.Dispose();
        return ptr;
      } else {
        return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  
    ~Position() {
      Dispose(false);
    }
  
    public void Dispose() {
      Dispose(true);
      global::System.GC.SuppressFinalize(this);
    }
  
    protected virtual void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            nrc_interfacePINVOKE.delete_VisionPositionParam_Position(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
      }
    }
  
    public int angleDirection {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Position_angleDirection_set(swigCPtr, value);
      } 
      get {
        int ret = nrc_interfacePINVOKE.VisionPositionParam_Position_angleDirection_get(swigCPtr);
        return ret;
      } 
    }
  
    public string cameraData {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Position_cameraData_set(swigCPtr, value);
        if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        string ret = nrc_interfacePINVOKE.VisionPositionParam_Position_cameraData_get(swigCPtr);
        if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public DoubleVector cameraPoint {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Position_cameraPoint_set(swigCPtr, DoubleVector.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionPositionParam_Position_cameraPoint_get(swigCPtr);
        DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
        return ret;
      } 
    }
  
    public DoubleVector datumPoint {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Position_datumPoint_set(swigCPtr, DoubleVector.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionPositionParam_Position_datumPoint_get(swigCPtr);
        DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
        return ret;
      } 
    }
  
    public DoubleVector datumPointDeg {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Position_datumPointDeg_set(swigCPtr, DoubleVector.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionPositionParam_Position_datumPointDeg_get(swigCPtr);
        DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
        return ret;
      } 
    }
  
      public class Excursion : global::System.IDisposable {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;
      
        internal Excursion(global::System.IntPtr cPtr, bool cMemoryOwn) {
          swigCMemOwn = cMemoryOwn;
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }
      
        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Excursion obj) {
          return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }
      
        internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Excursion obj) {
          if (obj != null) {
            if (!obj.swigCMemOwn)
              throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
            global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
            obj.swigCMemOwn = false;
            obj.Dispose();
            return ptr;
          } else {
            return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
          }
        }
      
        ~Excursion() {
          Dispose(false);
        }
      
        public void Dispose() {
          Dispose(true);
          global::System.GC.SuppressFinalize(this);
        }
      
        protected virtual void Dispose(bool disposing) {
          lock(this) {
            if (swigCPtr.Handle != global::System.IntPtr.Zero) {
              if (swigCMemOwn) {
                swigCMemOwn = false;
                nrc_interfacePINVOKE.delete_VisionPositionParam_Position_Excursion(swigCPtr);
              }
              swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
            }
          }
        }
      
        public double Xexcursion {
          set {
            nrc_interfacePINVOKE.VisionPositionParam_Position_Excursion_Xexcursion_set(swigCPtr, value);
          } 
          get {
            double ret = nrc_interfacePINVOKE.VisionPositionParam_Position_Excursion_Xexcursion_get(swigCPtr);
            return ret;
          } 
        }
      
        public double Yexcursion {
          set {
            nrc_interfacePINVOKE.VisionPositionParam_Position_Excursion_Yexcursion_set(swigCPtr, value);
          } 
          get {
            double ret = nrc_interfacePINVOKE.VisionPositionParam_Position_Excursion_Yexcursion_get(swigCPtr);
            return ret;
          } 
        }
      
        public double Zexcursion {
          set {
            nrc_interfacePINVOKE.VisionPositionParam_Position_Excursion_Zexcursion_set(swigCPtr, value);
          } 
          get {
            double ret = nrc_interfacePINVOKE.VisionPositionParam_Position_Excursion_Zexcursion_get(swigCPtr);
            return ret;
          } 
        }
      
        public double angle {
          set {
            nrc_interfacePINVOKE.VisionPositionParam_Position_Excursion_angle_set(swigCPtr, value);
          } 
          get {
            double ret = nrc_interfacePINVOKE.VisionPositionParam_Position_Excursion_angle_get(swigCPtr);
            return ret;
          } 
        }
      
        public Excursion() : this(nrc_interfacePINVOKE.new_VisionPositionParam_Position_Excursion(), true) {
        }
      
      }
  
    public VisionPositionParam.Position.Excursion excursion {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Position_excursion_set(swigCPtr, VisionPositionParam.Position.Excursion.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionPositionParam_Position_excursion_get(swigCPtr);
        VisionPositionParam.Position.Excursion ret = (cPtr == global::System.IntPtr.Zero) ? null : new VisionPositionParam.Position.Excursion(cPtr, false);
        return ret;
      } 
    }
  
    public int recvPointsType {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Position_recvPointsType_set(swigCPtr, value);
      } 
      get {
        int ret = nrc_interfacePINVOKE.VisionPositionParam_Position_recvPointsType_get(swigCPtr);
        return ret;
      } 
    }
  
    public string sampleData {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Position_sampleData_set(swigCPtr, value);
        if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        string ret = nrc_interfacePINVOKE.VisionPositionParam_Position_sampleData_get(swigCPtr);
        if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public double scale {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Position_scale_set(swigCPtr, value);
      } 
      get {
        double ret = nrc_interfacePINVOKE.VisionPositionParam_Position_scale_get(swigCPtr);
        return ret;
      } 
    }
  
    public Position() : this(nrc_interfacePINVOKE.new_VisionPositionParam_Position(), true) {
    }
  
  }

  public VisionPositionParam.Position position {
    set {
      nrc_interfacePINVOKE.VisionPositionParam_position_set(swigCPtr, VisionPositionParam.Position.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionPositionParam_position_get(swigCPtr);
      VisionPositionParam.Position ret = (cPtr == global::System.IntPtr.Zero) ? null : new VisionPositionParam.Position(cPtr, false);
      return ret;
    } 
  }

  public class Protocol : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal Protocol(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Protocol obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Protocol obj) {
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
        global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.Dispose();
        return ptr;
      } else {
        return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  
    ~Protocol() {
      Dispose(false);
    }
  
    public void Dispose() {
      Dispose(true);
      global::System.GC.SuppressFinalize(this);
    }
  
    protected virtual void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            nrc_interfacePINVOKE.delete_VisionPositionParam_Protocol(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
      }
    }
  
    public int type {
      set {
        nrc_interfacePINVOKE.VisionPositionParam_Protocol_type_set(swigCPtr, value);
      } 
      get {
        int ret = nrc_interfacePINVOKE.VisionPositionParam_Protocol_type_get(swigCPtr);
        return ret;
      } 
    }
  
    public Protocol() : this(nrc_interfacePINVOKE.new_VisionPositionParam_Protocol(), true) {
    }
  
  }

  public VisionPositionParam.Protocol protocol {
    set {
      nrc_interfacePINVOKE.VisionPositionParam_protocol_set(swigCPtr, VisionPositionParam.Protocol.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionPositionParam_protocol_get(swigCPtr);
      VisionPositionParam.Protocol ret = (cPtr == global::System.IntPtr.Zero) ? null : new VisionPositionParam.Protocol(cPtr, false);
      return ret;
    } 
  }

  public VisionPositionParam() : this(nrc_interfacePINVOKE.new_VisionPositionParam(), true) {
  }

}
