//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VisionCalibrationData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VisionCalibrationData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VisionCalibrationData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VisionCalibrationData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VisionCalibrationData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          nrc_interfacePINVOKE.delete_VisionCalibrationData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public class CalibrationPoint : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal CalibrationPoint(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CalibrationPoint obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CalibrationPoint obj) {
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
        global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.Dispose();
        return ptr;
      } else {
        return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  
    ~CalibrationPoint() {
      Dispose(false);
    }
  
    public void Dispose() {
      Dispose(true);
      global::System.GC.SuppressFinalize(this);
    }
  
    protected virtual void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            nrc_interfacePINVOKE.delete_VisionCalibrationData_CalibrationPoint(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
      }
    }
  
    public DoubleVector pixel_pos {
      set {
        nrc_interfacePINVOKE.VisionCalibrationData_CalibrationPoint_pixel_pos_set(swigCPtr, DoubleVector.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionCalibrationData_CalibrationPoint_pixel_pos_get(swigCPtr);
        DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
        return ret;
      } 
    }
  
    public DoubleVector pixel_pos_deg {
      set {
        nrc_interfacePINVOKE.VisionCalibrationData_CalibrationPoint_pixel_pos_deg_set(swigCPtr, DoubleVector.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionCalibrationData_CalibrationPoint_pixel_pos_deg_get(swigCPtr);
        DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
        return ret;
      } 
    }
  
    public DoubleVector robot_pos {
      set {
        nrc_interfacePINVOKE.VisionCalibrationData_CalibrationPoint_robot_pos_set(swigCPtr, DoubleVector.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionCalibrationData_CalibrationPoint_robot_pos_get(swigCPtr);
        DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
        return ret;
      } 
    }
  
    public DoubleVector robot_pos_deg {
      set {
        nrc_interfacePINVOKE.VisionCalibrationData_CalibrationPoint_robot_pos_deg_set(swigCPtr, DoubleVector.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionCalibrationData_CalibrationPoint_robot_pos_deg_get(swigCPtr);
        DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
        return ret;
      } 
    }
  
    public CalibrationPoint() : this(nrc_interfacePINVOKE.new_VisionCalibrationData_CalibrationPoint(), true) {
    }
  
  }

  public class Calibration : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal Calibration(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Calibration obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Calibration obj) {
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
        global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.Dispose();
        return ptr;
      } else {
        return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  
    ~Calibration() {
      Dispose(false);
    }
  
    public void Dispose() {
      Dispose(true);
      global::System.GC.SuppressFinalize(this);
    }
  
    protected virtual void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            nrc_interfacePINVOKE.delete_VisionCalibrationData_Calibration(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
      }
    }
  
    public bool calibrated {
      set {
        nrc_interfacePINVOKE.VisionCalibrationData_Calibration_calibrated_set(swigCPtr, value);
      } 
      get {
        bool ret = nrc_interfacePINVOKE.VisionCalibrationData_Calibration_calibrated_get(swigCPtr);
        return ret;
      } 
    }
  
    public SWIGTYPE_p_std__vectorT_VisionCalibrationData__CalibrationPoint_t point {
      set {
        nrc_interfacePINVOKE.VisionCalibrationData_Calibration_point_set(swigCPtr, SWIGTYPE_p_std__vectorT_VisionCalibrationData__CalibrationPoint_t.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionCalibrationData_Calibration_point_get(swigCPtr);
        SWIGTYPE_p_std__vectorT_VisionCalibrationData__CalibrationPoint_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_VisionCalibrationData__CalibrationPoint_t(cPtr, false);
        return ret;
      } 
    }
  
    public int point_num {
      set {
        nrc_interfacePINVOKE.VisionCalibrationData_Calibration_point_num_set(swigCPtr, value);
      } 
      get {
        int ret = nrc_interfacePINVOKE.VisionCalibrationData_Calibration_point_num_get(swigCPtr);
        return ret;
      } 
    }
  
    public void addCalibrationPoint(VisionCalibrationData.CalibrationPoint pos) {
      nrc_interfacePINVOKE.VisionCalibrationData_Calibration_addCalibrationPoint(swigCPtr, VisionCalibrationData.CalibrationPoint.getCPtr(pos));
      if (nrc_interfacePINVOKE.SWIGPendingException.Pending) throw nrc_interfacePINVOKE.SWIGPendingException.Retrieve();
    }
  
    public VisionCalibrationData.CalibrationPoint getPoint(int index) {
      VisionCalibrationData.CalibrationPoint ret = new VisionCalibrationData.CalibrationPoint(nrc_interfacePINVOKE.VisionCalibrationData_Calibration_getPoint(swigCPtr, index), true);
      return ret;
    }
  
    public Calibration(int num_points) : this(nrc_interfacePINVOKE.new_VisionCalibrationData_Calibration__SWIG_0(num_points), true) {
    }
  
    public Calibration() : this(nrc_interfacePINVOKE.new_VisionCalibrationData_Calibration__SWIG_1(), true) {
    }
  
  }

  public int visionNum {
    set {
      nrc_interfacePINVOKE.VisionCalibrationData_visionNum_set(swigCPtr, value);
    } 
    get {
      int ret = nrc_interfacePINVOKE.VisionCalibrationData_visionNum_get(swigCPtr);
      return ret;
    } 
  }

  public VisionCalibrationData.Calibration calibration {
    set {
      nrc_interfacePINVOKE.VisionCalibrationData_calibration_set(swigCPtr, VisionCalibrationData.Calibration.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = nrc_interfacePINVOKE.VisionCalibrationData_calibration_get(swigCPtr);
      VisionCalibrationData.Calibration ret = (cPtr == global::System.IntPtr.Zero) ? null : new VisionCalibrationData.Calibration(cPtr, false);
      return ret;
    } 
  }

  public VisionCalibrationData(int num_points) : this(nrc_interfacePINVOKE.new_VisionCalibrationData__SWIG_0(num_points), true) {
  }

  public VisionCalibrationData() : this(nrc_interfacePINVOKE.new_VisionCalibrationData__SWIG_1(), true) {
  }

}
